# Generated by Django 6.0.1 on 2026-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone', models.IntegerField()),
                ('android', models.IntegerField()),
                ('win', models.IntegerField()),
                ('mac', models.IntegerField()),
                ('others', models.IntegerField()),
            ],
        ),
    ]
